### ISSUE TITLE
Consider moving the map higher up under the page

### ISSUE THREAD

**Issue by rgdonohue** [ljmoser83/lex-foodscape#8]
Perhaps keep the Mission statement above the map and the other sections below?

**Comment by ljmoser83** [comment]
I adjusted this to test out your suggestion. I like it. What do you think? if it seems good, should I add nav buttons at the top right to take user directly to the definitions, below the map?

**Comment by rgdonohue** [comment]
@ljmoser83 Yeah, you all those navigational aids. Scrolling down is second-nature for humans now too, so they'll likely find them?
